/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 *
 * @author Allah
 */
@SuppressWarnings("SpellCheckingInspection")
public class Fehrest extends javax.swing.JFrame {

    /**
     * Creates new form Fehrest
     */
    public Fehrest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultState="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JButton btnBoz = new JButton();
        JButton btnJoje = new JButton();
        JButton btnForg = new JButton();
        JButton btnCow = new JButton();
        JButton btnZebra = new JButton();
        JButton btnOst = new JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton btnBack = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("برای دیدن آموزش ها روی آن ها کلیک نمایید.");

        btnBoz.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/bozf.jpg")))); // NOI18N
        btnBoz.addActionListener(this::btnBozActionPerformed);

        btnJoje.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/chicka.jpg")))); // NOI18N
        btnJoje.addActionListener(this::btnJojeActionPerformed);

        btnForg.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/frogf.jpg")))); // NOI18N
        btnForg.addActionListener(this::btnForgActionPerformed);

        btnCow.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/cow.jpg")))); // NOI18N
        btnCow.addActionListener(this::btnCowActionPerformed);

        btnZebra.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/zebra.jpg")))); // NOI18N
        btnZebra.addActionListener(this::btnZebraActionPerformed);

        btnOst.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/ostrichf.jpg")))); // NOI18N
        btnOst.addActionListener(this::btnOstrichfActionPerformed);

        btnBack.setBackground(new java.awt.Color(102, 153, 255));
        btnBack.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 0, 51));
        btnBack.setText("بازگشت");
        btnBack.addActionListener(evt -> btnBackActionPerformed());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBoz, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJoje, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCow, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnForg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOst, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZebra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBoz, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJoje, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCow, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnForg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOst, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZebra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnBack))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBozActionPerformed
        Boz boz = new Boz();
        this.setVisible(false);
        boz.setVisible(true);
    }//GEN-LAST:event_btnBozActionPerformed

    private void btnJojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJojeActionPerformed
        Joje j = new Joje();
        this.setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_btnJojeActionPerformed

    private void btnCowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCowActionPerformed
       Cow c = new Cow();
       this.setVisible(false);
       c.setVisible(true);
    }//GEN-LAST:event_btnCowActionPerformed

    private void btnForgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgActionPerformed
        Forg f =new Forg();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_btnForgActionPerformed

    private void btnOstrichfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOstrichfActionPerformed
        Ostrich os = new Ostrich();
        this.setVisible(false);
        os.setVisible(true);
    }//GEN-LAST:event_btnOstrichfActionPerformed

    private void btnZebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZebraActionPerformed
        Zebra z = new Zebra();
        this.setVisible(false);
        z.setVisible(true);
    }//GEN-LAST:event_btnZebraActionPerformed

    private void btnBackActionPerformed() {//GEN-FIRST:event_btnBackActionPerformed
        Page1 p1 = new Page1();
        this.setVisible(false);
        p1.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultState="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fehrest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fehrest().setVisible(true));
    }

    // End of variables declaration//GEN-END:variables
}
