
import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Allah
 */
public class Forg extends javax.swing.JFrame {

    /**
     * Creates new form Forg
     */
    
    ImageIcon[] img;
    int step=0;
    
    public Forg() {
        initComponents();
        btnNext.setVisible(false);
        btnPrevious.setVisible(false);
        lblStep.setVisible(false);
        lblStepByStep.setVisible(false);
        btnBack.setVisible(false);
        lblShow.setIcon(new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/frogf.jpg"))));
        img = new ImageIcon[4];
        img[0]= new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/frog_1.jpg")));
        img[1]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/frog_2.jpg")));
        img[2]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/frog_3.jpg")));
        img[3]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/frog_4.jpg")));
    }
    
    private int ImageCount()
    {
        return img.length;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultState="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        lblShow = new javax.swing.JLabel();
        lblStep = new javax.swing.JLabel();
        lblStepByStep = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("قورباغه");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblStep.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 18)); // NOI18N
        lblStep.setForeground(new java.awt.Color(255, 0, 51));
        lblStep.setText("مرحله :");

        lblStepByStep.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        lblStepByStep.setForeground(new java.awt.Color(0, 51, 204));
        lblStepByStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStepByStep.setText("---");

        btnPrevious.setBackground(new java.awt.Color(204, 0, 204));
        btnPrevious.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        btnPrevious.setText("گام قبلی");
        btnPrevious.addActionListener(evt -> btnPreviousActionPerformed());

        btnStart.setBackground(new java.awt.Color(204, 0, 204));
        btnStart.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 12)); // NOI18N
        btnStart.setText("شروع کن");
        btnStart.addActionListener(evt -> btnStartActionPerformed());

        btnNext.setBackground(new java.awt.Color(204, 0, 204));
        btnNext.setFont(new java.awt.Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        btnNext.setText("گام بعدی");
        btnNext.addActionListener(evt -> btnNextActionPerformed());

        btnBack.setForeground(new java.awt.Color(255, 0, 102));
        btnBack.setText("بازگشت");
        btnBack.addActionListener(evt -> btnBackActionPerformed());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblShow, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblStepByStep, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStep))
                            .addComponent(btnBack))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblShow, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStep)
                    .addComponent(lblStepByStep, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed() {//GEN-FIRST:event_btnBackActionPerformed
       Fehrest f = new Fehrest();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed() {//GEN-FIRST:event_btnNextActionPerformed
        step++;
        if (step > ImageCount()) {
            step = 1;
        }
        lblShow.setIcon(img[step-1]);
        lblStepByStep.setText(step +"از"+ ImageCount());
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed() {//GEN-FIRST:event_btnPreviousActionPerformed
       step--;
        if(step>0 && step<=ImageCount())
        {
            lblShow.setIcon(img[step-1]);
            lblStepByStep.setText(step +"از"+ ImageCount());
        }
        else if(step<=0)
        {
            step=ImageCount();
            lblShow.setIcon(img[step-1]);
            lblStepByStep.setText(step +"از"+ ImageCount());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnStartActionPerformed() {//GEN-FIRST:event_btnStartActionPerformed
       btnNext.setVisible(true);
       btnPrevious.setVisible(true);
       lblStep.setVisible(true);
       lblStepByStep.setVisible(true);
       btnStart.setVisible(false);
       btnBack.setVisible(true);
       
       step++;
        lblStepByStep.setText(step +"از"+ ImageCount());
       lblShow.setIcon((img[0]));
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultState="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Forg().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblShow;
    private javax.swing.JLabel lblStep;
    private javax.swing.JLabel lblStepByStep;
    // End of variables declaration//GEN-END:variables
}
