
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Allah
 */
public class Ostrich extends JFrame {

    /**
     * Creates new form Ostrich
     */
    
    ImageIcon[] img;
    int step=0;
    
    public Ostrich() {
        initComponents();
        btnNext.setVisible(false);
        btnPrevious.setVisible(false);
        lblStep.setVisible(false);
        lblStepByStep.setVisible(false);
        btnBack.setVisible(false);
        lblShow.setIcon(new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrichf.jpg"))));
        img = new ImageIcon[6];
        img[0]= new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrich_1.jpg")));
        img[1]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrich_2.jpg")));
        img[2]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrich_3.jpg")));
        img[3]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrich_4.jpg")));
        img[4]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrich_5.jpg")));
        img[5]=new ImageIcon(Objects.requireNonNull(this.getClass().getResource("/ostrich_6.jpg")));
    }
    
     private int ImageCount()
    {
        return img.length;
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultState="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        lblShow = new JLabel();
        lblStep = new JLabel();
        lblStepByStep = new JLabel();
        btnNext = new JButton();
        btnPrevious = new JButton();
        btnStart = new JButton();
        btnBack = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("شترمرغ");

        jPanel1.setBackground(new Color(255, 255, 255));

        lblShow.setHorizontalAlignment(SwingConstants.CENTER);

        lblStep.setFont(new Font("Vazirmatn", Font.BOLD, 18)); // NOI18N
        lblStep.setForeground(new Color(255, 0, 51));
        lblStep.setText("مرحله :");

        lblStepByStep.setFont(new Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        lblStepByStep.setForeground(new Color(0, 51, 204));
        lblStepByStep.setHorizontalAlignment(SwingConstants.CENTER);
        lblStepByStep.setText("---");

        btnNext.setBackground(new Color(204, 0, 204));
        btnNext.setFont(new Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        btnNext.setText("گام بعدی");
        btnNext.addActionListener(evt -> btnNextActionPerformed());

        btnPrevious.setBackground(new Color(204, 0, 204));
        btnPrevious.setFont(new Font("Vazirmatn", Font.BOLD, 14)); // NOI18N
        btnPrevious.setText("گام قبلی");
        btnPrevious.addActionListener(evt -> btnPreviousActionPerformed());

        btnStart.setBackground(new Color(204, 0, 204));
        btnStart.setFont(new Font("Vazirmatn", Font.BOLD, 12)); // NOI18N
        btnStart.setText("شروع کن");
        btnStart.addActionListener(evt -> btnStartActionPerformed());

        btnBack.setForeground(new Color(255, 0, 102));
        btnBack.setText("بازگشت");
        btnBack.addActionListener(this::btnBackActionPerformed);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrevious)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblShow, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblStepByStep, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStep))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btnStart, GroupLayout.PREFERRED_SIZE, 181, GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblShow, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStep)
                    .addComponent(lblStepByStep, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnStart, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnBack))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Fehrest f = new Fehrest();
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed() {//GEN-FIRST:event_btnNextActionPerformed
        step++;
        if (step > ImageCount()) {
            step = 1;
        }
        lblShow.setIcon(img[step-1]);
        lblStepByStep.setText(step +"از"+ ImageCount());
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed() {//GEN-FIRST:event_btnPreviousActionPerformed
       step--;
        if(step>0 && step<=ImageCount())
        {
            lblShow.setIcon(img[step-1]);
            lblStepByStep.setText(step +"از"+ ImageCount());
        }
        else if(step<=0)
        {
            step=ImageCount();
            lblShow.setIcon(img[step-1]);
            lblStepByStep.setText(step +"از"+ ImageCount());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnStartActionPerformed() {//GEN-FIRST:event_btnStartActionPerformed
       btnNext.setVisible(true);
       btnPrevious.setVisible(true);
       lblStep.setVisible(true);
       lblStepByStep.setVisible(true);
       btnStart.setVisible(false);
       btnBack.setVisible(true);
       
       step++;
        lblStepByStep.setText(step +"از"+ ImageCount());
       lblShow.setIcon((img[0]));
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultState="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException |
                 IllegalAccessException ex) {
            Logger.getLogger(Ostrich.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new Ostrich().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnBack;
    private JButton btnNext;
    private JButton btnPrevious;
    private JButton btnStart;
    private JLabel lblShow;
    private JLabel lblStep;
    private JLabel lblStepByStep;
    // End of variables declaration//GEN-END:variables
}
